#aircraft parameters

TURN_RATE = 3
CLIMB_RATE = 20
DESCENT_RATE = 20
EXP_DESCENT_RATE = 30
SPEED_CHANGE_RATE = 2
EXP_SPEED_CHANGE_RATE = 4
TRAJ_LENGTH = 10
SHORT_FINAL_IAS = 140
GROUND_DECELERATION_RATE = 3

#airline names

CALLSIGN_PREFIXES = ["DL", "BA", "AF", "LH", "UA", "AA"]