"""Parallel rollout collection for multi-plane PPO (Phase 1).

Mirrors `rl_ppo.rollout` — multi-process worker pool, each holding its
own MultiPPOEnv + CombinedPolicy, broadcasts policy state every iter,
returns full trajectories.

Key difference from rl_ppo: stored `actions` are 3-D deltas (the PPO
action), not 4-D env-format. The env-format command is regenerated by
the policy at update time only if needed (not needed for the PPO
loss — only log_prob / entropy on the delta matters).
"""
from __future__ import annotations

import multiprocessing as mp
import os
import time
from dataclasses import dataclass
from pathlib import Path

import numpy as np


@dataclass
class Trajectory:
    obs: np.ndarray           # (T, 79) standardized full obs (ego + density)
    ego_obs: np.ndarray       # (T, 7)  the slice the frozen GMM sees
    actions: np.ndarray       # (T, 3)  delta — (Δhdg_deg, Δalt_kft, Δspd_kt)
    log_probs: np.ndarray     # (T,)
    rewards: np.ndarray       # (T,)
    values: np.ndarray        # (T,)
    dones: np.ndarray         # (T,) bool
    star: str
    outcome: str
    steps: int
    # Per-episode metadata. Useful for rollouts.csv / debugging — let
    # downstream tools tie an outcome to a specific spawn.
    seed: int = 0
    callsign: str = ''
    error: str | None = None
    d_thr_nm: float | None = None
    altitude_ft: float | None = None
    gs_alt_ft: float | None = None
    a_traj: np.ndarray | None = None
    c_traj: np.ndarray | None = None
    n_loop_steps: int = 0
    n_penalized: int = 0
    loop_penalty_total: float = 0.0


# --------------------------------------------------------------------------- #
# Worker globals (one per child process)
# --------------------------------------------------------------------------- #


_ENV = None
_POLICY = None
_CONFIG = None
_EGO_DIM = 7
_FULL_DIM = 79


def _init_worker(ppo_ckpt: str, bc_seed: str, cfg_dict: dict) -> None:
    os.environ['OMP_NUM_THREADS'] = '1'
    os.environ['MKL_NUM_THREADS'] = '1'
    os.environ['OPENBLAS_NUM_THREADS'] = '1'
    import torch
    torch.set_num_threads(1)

    global _ENV, _POLICY, _CONFIG, _EGO_DIM, _FULL_DIM
    from rl_ppo import reward_zones as _rz
    from rl_multiple.env import MultiPPOEnv
    from rl_multiple.policy import CombinedPolicy
    _CONFIG = cfg_dict

    # CRITICAL: apply reward overrides INSIDE the worker (spawn-mode
    # processes don't inherit module state — same trap as rl_ppo.rollout).
    _rz.set_runtime_overrides(
        everywhere_step_penalty=cfg_dict.get('reward_everywhere_step_penalty'),
        step_penalty_cap=cfg_dict.get('reward_step_penalty_cap'),
        step_penalty_per_nm=cfg_dict.get('reward_step_penalty_per_nm'),
        early_zone_multiplier=cfg_dict.get('reward_early_zone_multiplier'),
        early_window_steps=cfg_dict.get('reward_early_window_steps'),
        early_drift_penalty=cfg_dict.get('reward_early_drift_penalty'),
        clean_terminal_threshold=cfg_dict.get('reward_clean_terminal_threshold'),
        drifty_success_value=cfg_dict.get('reward_drifty_success_value'),
        out_of_zone_terminate=cfg_dict.get('reward_out_of_zone_terminate'),
        out_of_zone_max_consecutive=cfg_dict.get('reward_out_of_zone_max_consecutive'),
        per_star_sr_scale=cfg_dict.get('reward_per_star_sr_scale'),
        per_star_recent_sr=cfg_dict.get('reward_per_star_recent_sr'),
    )

    # MultiPPOEnv takes the SAME actor_ckpt as PPOEnv (BC seed, for
    # standardizer + arch). The frozen GMM weights come from the PPO
    # ckpt and are loaded inside CombinedPolicy.from_ppo_ckpt below.
    _ENV = MultiPPOEnv(
        actor_ckpt=bc_seed,
        airport_name=cfg_dict['airport_name'],
        runway=cfg_dict['runway'],
        warmup_wpts=cfg_dict['warmup_wpts'],
        max_timesteps_star_1_2=cfg_dict['max_timesteps_star_1_2'],
        max_timesteps_star_3=cfg_dict['max_timesteps_star_3'],
        success_reward=cfg_dict['success_reward'],
        failure_reward=cfg_dict['failure_reward'],
        gs_capture_buffer_ft=cfg_dict.get('gs_capture_buffer_ft', 50.0),
        density_cutoff_nm=cfg_dict.get('density_cutoff_nm', 10.0),
    )
    _EGO_DIM = _ENV._ego_obs_dim
    _FULL_DIM = _ENV.obs_dim

    _POLICY = CombinedPolicy.from_ppo_ckpt(
        ppo_ckpt,
        bc_seed_path=bc_seed,
        density_n_bins=cfg_dict.get('density_n_bins', 36),
        delta_hidden=cfg_dict.get('delta_hidden', 64),
        value_hidden=cfg_dict.get('value_hidden', 64),
        value_dropout=cfg_dict.get('value_dropout', 0.0),
        device='cpu',
    )
    _POLICY.eval()


def _run_episode(job: tuple) -> dict:
    """Roll one episode. job = (star, seed, policy_state)."""
    import traceback
    import torch

    star, seed, policy_state = job
    try:
        if policy_state is not None:
            _POLICY.load_state_split(policy_state, device='cpu')

        full_obs = _ENV.reset(star=star, seed=seed)

        callsign = _ENV._callsign or '?'
        fm_seed = (hash((callsign, seed)) & 0x7FFFFFFF) or 1
        gen = torch.Generator(device='cpu')

        obs_list: list[np.ndarray] = []
        ego_obs_list: list[np.ndarray] = []
        act_list: list[np.ndarray] = []     # 3-D deltas
        lp_list: list[float] = []
        rw_list: list[float] = []
        val_list: list[float] = []
        done_list: list[bool] = []
        a_list: list[float] = []
        c_list: list[float] = []

        outcome = 'UNKNOWN'
        n_steps = 0
        err: str | None = None
        final_info: dict = {}
        while True:
            full_t = torch.from_numpy(full_obs).unsqueeze(0)
            ego_t = full_t[:, :_EGO_DIM]
            gen.manual_seed(fm_seed)
            out = _POLICY.act(ego_t, full_t, generator=gen)
            delta = out['action_delta'].squeeze(0).cpu().numpy()
            final = out['action_final'].squeeze(0).cpu().numpy()
            log_prob = float(out['log_prob'].squeeze(0).item())
            value = float(out['value'].squeeze(0).item())

            step = _ENV.step(final)
            obs_list.append(full_obs.copy())
            ego_obs_list.append(full_obs[:_EGO_DIM].copy())
            act_list.append(delta.astype(np.float32))
            lp_list.append(log_prob)
            val_list.append(value)
            rw_list.append(float(step.reward))
            done_list.append(bool(step.done))
            a_list.append(float(step.info.get('a_nm', float('nan'))))
            c_list.append(float(step.info.get('c_nm', float('nan'))))
            n_steps += 1
            full_obs = step.obs
            if step.done:
                outcome = step.info.get('outcome', 'UNKNOWN')
                err = step.info.get('error')
                final_info = step.info
                break

        rewards = np.asarray(rw_list, dtype=np.float32)
        a_traj = np.asarray(a_list, dtype=np.float32)
        c_traj = np.asarray(c_list, dtype=np.float32)

        # Post-hoc loop penalty (same as rl_ppo.rollout). Skipped when
        # cfg.loop_penalty_per_step == 0.
        loop_pps = float(_CONFIG.get('loop_penalty_per_step', 0.0) or 0.0)
        n_loop_steps = 0
        n_penalized = 0
        loop_penalty_total = 0.0
        if loop_pps > 0.0 and a_traj.size >= 2:
            from rl_ppo.loop_detector import detect_looping
            d = detect_looping(
                a_traj, c_traj,
                prox_radius_nm=float(_CONFIG.get('loop_prox_radius_nm', 0.75)),
                min_gap_steps=int(_CONFIG.get('loop_min_gap_steps', 45)),
                min_detour_nm=float(_CONFIG.get('loop_min_detour_nm', 1.0)),
                min_loop_frac=0.0,
            )
            mask = d['looping_step_mask']
            if mask.any():
                loop_indices = np.flatnonzero(mask)
                k = int(loop_indices.size)
                half = (k + 1) // 2
                penalize = loop_indices[half:]
                n_loop_steps = k
                n_penalized = int(penalize.size)
                if n_penalized > 0:
                    rewards[penalize] -= loop_pps
                    loop_penalty_total = float(loop_pps * n_penalized)

        return {
            'ok': True,
            'star': star, 'seed': seed, 'callsign': callsign,
            'outcome': outcome, 'steps': n_steps, 'error': err,
            'obs': np.stack(obs_list).astype(np.float32),
            'ego_obs': np.stack(ego_obs_list).astype(np.float32),
            'actions': np.stack(act_list).astype(np.float32),
            'log_probs': np.asarray(lp_list, dtype=np.float32),
            'rewards': rewards,
            'values': np.asarray(val_list, dtype=np.float32),
            'dones': np.asarray(done_list, dtype=bool),
            'a_traj': a_traj,
            'c_traj': c_traj,
            'd_thr_nm': final_info.get('d_thr_nm'),
            'altitude_ft': final_info.get('altitude_ft'),
            'gs_alt_ft': final_info.get('gs_alt_ft'),
            'n_loop_steps': n_loop_steps,
            'n_penalized': n_penalized,
            'loop_penalty_total': loop_penalty_total,
        }
    except Exception as exc:
        return {
            'ok': False,
            'star': star, 'seed': seed,
            'outcome': 'WORKER_CRASHED',
            'error': f"{type(exc).__name__}: {exc}",
            'traceback': traceback.format_exc(limit=4),
        }


# --------------------------------------------------------------------------- #
# Main-process orchestration
# --------------------------------------------------------------------------- #


def make_rollout_pool(ppo_ckpt: str, bc_seed: str, cfg_dict: dict,
                      n_workers: int):
    """Create the pool once and reuse it across PPO iterations."""
    return mp.Pool(n_workers, initializer=_init_worker,
                   initargs=(str(ppo_ckpt), str(bc_seed), cfg_dict))


# --------------------------------------------------------------------------- #
# Multi-plane rollout collection (Phase 2).
# Each worker owns one MultiRolloutSim and collects until its quota of
# trajectories is done. The pool itself is shared with the single-plane
# path: workers init both paths and the dispatch is per-job.
# --------------------------------------------------------------------------- #


_MULTI_SIM = None


def _init_multi_worker(ppo_seed_ckpt: str, bc_seed_ckpt: str,
                        cfg_dict: dict, worker_id: int) -> None:
    """Worker initializer for the multi-plane path. Builds one
    MultiRolloutSim per worker; the sim is reused across iters."""
    os.environ['OMP_NUM_THREADS'] = '1'
    os.environ['MKL_NUM_THREADS'] = '1'
    os.environ['OPENBLAS_NUM_THREADS'] = '1'
    import torch
    torch.set_num_threads(1)

    global _MULTI_SIM
    from rl_multiple.multi_env import MultiRolloutSim
    replay_dir = cfg_dict.get('replay_dir')
    _MULTI_SIM = MultiRolloutSim(
        ppo_seed_ckpt=ppo_seed_ckpt,
        bc_seed_ckpt=bc_seed_ckpt,
        cfg_dict=cfg_dict,
        worker_id=worker_id,
        replay_dir=replay_dir,
    )


def _run_multi(job: tuple) -> dict:
    """One worker collects `n_target` trajectories via its MultiRolloutSim."""
    import traceback
    n_target, policy_state, max_ticks, drop_truncated = job
    try:
        trajs, stats = _MULTI_SIM.collect(
            n_target=n_target,
            policy_state=policy_state,
            max_ticks=max_ticks,
            drop_truncated=drop_truncated,
        )
        return {'ok': True, 'trajectories': trajs, 'stats': stats}
    except Exception as exc:
        return {
            'ok': False,
            'outcome': 'WORKER_CRASHED',
            'error': f"{type(exc).__name__}: {exc}",
            'traceback': traceback.format_exc(limit=4),
        }


def make_multi_pool(ppo_seed_ckpt: str, bc_seed_ckpt: str,
                     cfg_dict: dict, n_workers: int):
    """Spawn-mode pool. Each worker gets a unique worker_id so seeds
    don't collide and replay CSVs don't overwrite."""
    # `mp.Pool` initializer doesn't take per-worker args natively, so
    # we use a trick: each worker computes its id from the order it
    # joins via a shared counter. Simpler: use spawn-init that pulls
    # worker_id from an env var set per-process. But that's complex
    # to set from the parent. Cleanest is to skip the per-worker id
    # — just use the OS pid as a unique-ish discriminator.
    import os as _os
    return mp.Pool(
        n_workers,
        initializer=_init_multi_worker,
        initargs=(str(ppo_seed_ckpt), str(bc_seed_ckpt), cfg_dict, _os.getpid()),
    )


def collect_multi_rollouts(pool,
                            n_target_total: int,
                            policy_state: dict,
                            max_ticks_per_worker: int = 30_000,
                            drop_truncated: bool = True,
                            verbose: bool = True) -> tuple:
    """Distribute `n_target_total` trajectories across pool workers.
    Returns (trajectories, stats_aggregate).

    `drop_truncated`: when True (default), each worker keeps rolling
    until it has `per_worker` NON-TRUNCATED trajectories, then drops
    its TRUNCATED ones. Cleaner training signal at the cost of more
    sim time per iter."""
    n_workers = pool._processes
    per_worker = (n_target_total + n_workers - 1) // n_workers   # ceil
    jobs = [(per_worker, policy_state, max_ticks_per_worker, drop_truncated)
            for _ in range(n_workers)]
    t0 = time.time()
    all_trajs: list = []
    total_crashes = 0
    total_restarts = 0
    total_ticks = 0
    total_raw = 0
    total_truncated_dropped = 0
    n_done = 0
    for r in pool.imap_unordered(_run_multi, jobs, chunksize=1):
        n_done += 1
        if not r.get('ok'):
            if verbose:
                print(f"  [{n_done}/{n_workers}] worker CRASHED: "
                      f"{r.get('error', '?')}", flush=True)
            continue
        all_trajs.extend(r['trajectories'])
        st = r['stats']
        total_crashes += st['n_crashes']
        total_restarts += st['n_sim_restarts']
        total_ticks += st['n_ticks']
        total_raw += st.get('n_raw_trajectories', st['n_trajectories'])
        total_truncated_dropped += st.get('n_truncated_dropped', 0)
    # Truncate to target (workers over-fill slightly due to per_worker rounding).
    all_trajs = all_trajs[:n_target_total]
    if verbose:
        elapsed = time.time() - t0
        msg = (f"  multi-rollouts: {len(all_trajs)} trajs  "
               f"raw={total_raw}  trunc-dropped={total_truncated_dropped}  "
               f"crashes={total_crashes}  sim_restarts={total_restarts}  "
               f"ticks={total_ticks}  in {elapsed:.1f}s")
        print(msg, flush=True)
    return all_trajs, {
        'n_trajectories': len(all_trajs),
        'n_raw_trajectories': total_raw,
        'n_truncated_dropped': total_truncated_dropped,
        'n_crashes': total_crashes,
        'n_sim_restarts': total_restarts,
        'n_ticks': total_ticks,
    }


def collect_rollouts(pool, n_rollouts: int, stars: tuple,
                     seed_offset: int, policy_state: dict,
                     verbose: bool = True) -> list[Trajectory]:
    n_stars = len(stars)
    base_per_star = n_rollouts // n_stars
    remainder = n_rollouts - base_per_star * n_stars
    jobs = []
    seed = seed_offset
    for i, star in enumerate(stars):
        k = base_per_star + (1 if i < remainder else 0)
        for _ in range(k):
            jobs.append((star, seed, policy_state))
            seed += 1

    t0 = time.time()
    trajectories: list[Trajectory] = []
    n_done = 0
    n_success = 0
    n_crashed = 0
    for r in pool.imap_unordered(_run_episode, jobs, chunksize=1):
        n_done += 1
        if not r.get('ok'):
            n_crashed += 1
            if verbose:
                print(f"  [{n_done}/{len(jobs)}] WORKER_CRASHED "
                      f"{r['star']} seed={r['seed']}: {r.get('error', '?')}",
                      flush=True)
            continue
        traj = Trajectory(
            obs=r['obs'], ego_obs=r['ego_obs'], actions=r['actions'],
            log_probs=r['log_probs'], rewards=r['rewards'],
            values=r['values'], dones=r['dones'],
            star=r['star'], outcome=r['outcome'],
            steps=r['steps'],
            seed=int(r.get('seed', 0)),
            callsign=str(r.get('callsign', '')),
            error=r.get('error'),
            d_thr_nm=r.get('d_thr_nm'),
            altitude_ft=r.get('altitude_ft'),
            gs_alt_ft=r.get('gs_alt_ft'),
            a_traj=r.get('a_traj'),
            c_traj=r.get('c_traj'),
            n_loop_steps=int(r.get('n_loop_steps', 0)),
            n_penalized=int(r.get('n_penalized', 0)),
            loop_penalty_total=float(r.get('loop_penalty_total', 0.0)),
        )
        if traj.outcome == 'LOC_BELOW_GS':
            n_success += 1
        trajectories.append(traj)

    if verbose:
        elapsed = time.time() - t0
        print(f"  rollouts: {len(trajectories)} ok ({n_success} success, "
              f"{n_crashed} crashed) in {elapsed:.1f}s "
              f"({sum(t.steps for t in trajectories)} env steps total)",
              flush=True)
    return trajectories
